CREATE TABLE EBM(
	RID VARCHAR(50) NOT NULL PRIMARY KEY,
	ChartNo VARCHAR(50) NOT NULL,
	[Status] VARCHAR(5)
)

CREATE TABLE EBMOupt(
	RID VARCHAR(50) NOT NULL PRIMARY KEY,
	ChartNo VARCHAR(50) NOT NULL,
	[Status] VARCHAR(5)
)

INSERT INTO EBM VALUES ('000001511','2623016','C')
INSERT INTO EBM VALUES ('000001512','2623017','B')
INSERT INTO EBM VALUES ('000001513','2623018','A')



CREATE TYPE [dbo].[utff_chartNo] AS TABLE
(
    chartNo VARCHAR(50)
)


CREATE TYPE [dbo].[utff_RID] AS TABLE
(
    RID VARCHAR(50)
)

CREATE TYPE [dbo].[utff_EMB] AS TABLE
(
	RID VARCHAR(50),
	ChartNo VARCHAR(50),
	[STATUS] VARCHAR(5)
)

CREATE OR ALTER PROCEDURE dbo.GetALL_EBM
AS
BEGIN
	SET NOCOUNT ON;
	SELECT RID,ChartNo,[Status]
	FROM dbo.EBM
END 



CREATE OR ALTER PROCEDURE dbo.GetEBMByRID(
	@Rid dbo.[utff_RID]  READONLY
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT e.RID,e.ChartNo,e.[Status]
	FROM dbo.EBM e JOIN @Rid c 
	ON c.RID = e.RID
END 


CREATE OR ALTER PROCEDURE dbo.GetEBMByChartNo(
	@chartNo dbo.[utff_chartNo]  READONLY
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT e.RID,e.ChartNo,e.[Status]
	FROM dbo.EBM e JOIN @chartNo c 
	ON c.chartno = e.chartno
END 


CREATE OR ALTER PROCEDURE dbo.InsertEBMData
	@EMB dbo.utff_EMB READONLY
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO dbo.EBMOutput (RID,ChartNo,[Status])
	SELECT RID,ChartNo,[Status]
	FROM @EMB eo
	WHERE NOT EXISTS(
		SELECT 1 
		FROM EBMOutput e
		WHERE e.RID = eo.RID
	)
END 




